name: Test my app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        id: tests
        uses: mauricio-chavez/deno-test-action@v1
        with:
          tests: 'app.test.ts'
