name: Test my app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - run: deno test
